# Generated by Django 3.0.8 on 2020-08-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20200807_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
