# Generated by Django 3.0.8 on 2020-08-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_follow_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
