# Generated by Django 3.0.8 on 2020-08-11 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_likes_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
