# Generated by Django 3.0.8 on 2020-08-11 08:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20200811_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='user_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
